version: "3.5"
services:
  db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  health:
    build: .
    ports:
      - 5000:5000
    environment:
      DB_URL: "postgres://admin:admin@db:5432/admin" 
    depends_on:
      - db
